### ISSUE TITLE
Customize on which page snow appears

### ISSUE THREAD

**Issue by PVince81** [tomneedham/oc_xmas#1]
I find it annoying to see snow on the files app and it might also eat CPU resource if you have multiple tabs open.

Would be good to have an option to only enable/disable this on the following page:

- public links
- login page / error page (full-screen pages)
- current app

Reason is that some companies might enable this app for the ambience but might be put off by the fact it might decrease productivity when working in the browser.

**Comment by tomneedham** [comment]
We already received this as a request from a nice big instance - I shall implement this this evening.

**Comment by tomneedham** [comment]
implemented!
